--- I'll create a schema for the traffic_accidents.csv database

CREATE TABLE if not EXISTS traffic_accidents (
    crash_date date,
    traffic_control_device VARCHAR(100) ,
    weather_condition varchar(255) ,
    lighting_condition VARCHAR(255) ,
    first_crash_type VARCHAR(255) ,
    trafficway_type varchar(255) ,
    alignment varchar(100) , 
    roadway_surface_cond varchar(255) ,
    road_defect varchar(255) , 
    crash_type varchar(255) ,
    intersection_related_i varchar(255) ,
    damage varchar(255) ,
    prim_contributory_cause varchar(255) ,
    num_units int ,
    most_severe_injury varchar(255) ,
    injuries_total smallint ,
    injuries_fatal smallint ,
    injuries_incapacitating smallint ,
    injuries_non_incapacitating smallint ,
    injuries_reported_not_evident smallint ,
    injuries_no_indication smallint,
    crash_hour smallint,
    crash_day_of_week smallint,
    crash_month smallint,
     --  FEATURE ENGINEERING (NEW COLUMNS)
    severity_score INT,
    is_severe BOOLEAN,
    multi_unit BOOLEAN,
    day_type VARCHAR(10),
    time_of_day VARCHAR(20),
    season VARCHAR(10),
    month_name VARCHAR(20),
    damage_level VARCHAR(20),
    cause_category VARCHAR(20),
    is_driver_related BOOLEAN,
    is_road_related BOOLEAN,
    is_environment_related BOOLEAN,
    is_unknown_cause BOOLEAN,
    is_other_cause BOOLEAN
);


